#!/usr/bin/env bash
# Installs the `socius` command as a thin wrapper that runs the CLI from this
# repo via Bun (no build step — Bun runs the TypeScript directly).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUN="$(command -v bun || echo "$HOME/.bun/bin/bun")"
BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"

if [ ! -x "$BUN" ]; then
  echo "error: bun not found. Install Bun first: https://bun.sh" >&2
  exit 1
fi

mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/socius" <<EOF
#!/usr/bin/env bash
# Socius CLI launcher (generated by scripts/install.sh).
exec "$BUN" run "$REPO/packages/cli/src/main.ts" "\$@"
EOF
chmod +x "$BIN_DIR/socius"

echo "Installed: $BIN_DIR/socius  ->  $REPO"
case ":$PATH:" in
  *":$BIN_DIR:"*) echo "Run 'socius doctor' to verify." ;;
  *) echo "Note: $BIN_DIR is not on your PATH. Add it to your shell profile, e.g.:"
     echo "  export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac
